http:
  private:
    host: "0.0.0.0"
    port: "8091"
    
app:
  version: "1.0.0"
  name: "kcc-mkt-stratifyd-exp-api"
  source: "Marketing"
   
hana:
  user: "APP_CHINA_DL_4C"
  password: "AppChina2020@"
  url: "jdbc:sap://dev-hana.kcc.com:30115"
  
api:
  id: ""  
    